"""Where the moving background behind the captions comes from.

Two providers behind one interface:

* **Library** -- gameplay footage from `assets/backgrounds`. The clip and its
  start offset are chosen deterministically from the story id, so a re-render
  produces an identical file, and two consecutive videos do not open on the same
  frame of the same clip.
* **Procedural** -- an animated gradient generated by ffmpeg itself.

The procedural provider is not a placeholder. It renders a real, varied,
watchable background, and it exists so the pipeline is complete and testable
*before* any footage exists. In `auto` mode the library takes over the moment
usable clips appear in the directory, with no configuration change.

Selection is by `blake2b` of the seed rather than `hash()`: the built-in is
randomised per process by PYTHONHASHSEED, which would make renders
irreproducible across restarts for no reason.
"""

from __future__ import annotations

import hashlib
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, runtime_checkable

from pulpmill.config.models import BackgroundConfig, ProceduralBackgroundConfig
from pulpmill.domain.errors import AssetError
from pulpmill.infrastructure.logging import get_logger
from pulpmill.rendering.ffmpeg import MediaInfo, probe

_log = get_logger("rendering.backgrounds")

PROCEDURAL_SOURCE = "procedural"


def seed_int(*parts: str) -> int:
    """Stable integer from arbitrary strings. Reproducible across processes."""
    digest = hashlib.blake2b(b"\x1f".join(part.encode("utf-8") for part in parts), digest_size=8)
    return int.from_bytes(digest.digest(), "big")


@dataclass(frozen=True, slots=True)
class BackgroundSource:
    """A resolved background, expressed as ffmpeg input arguments.

    `input_args` produces exactly one video input. The compositor is responsible
    for scaling and cropping it to frame; this type only decides *what* is fed
    in and from where.
    """

    kind: str
    #: Clip filename, or "procedural". Stored on the video artifact so a batch
    #: sharing footage is findable after the fact.
    name: str
    input_args: tuple[str, ...]
    start_offset_seconds: float = 0.0
    #: Set when the source is a finite clip shorter than the video, and has
    #: therefore been told to loop.
    looped: bool = False


@runtime_checkable
class BackgroundProvider(Protocol):
    @property
    def name(self) -> str: ...

    def available(self) -> tuple[bool, str]:
        """Whether this provider can supply a background right now."""
        ...

    def resolve(
        self, *, seed: str, duration_seconds: float, width: int, height: int, fps: int
    ) -> BackgroundSource: ...


class ProceduralBackgroundProvider:
    """An animated gradient, generated by ffmpeg's `gradients` source.

    Varied per story by deriving the gradient's angle and drift speed from the
    seed, so a run of videos does not look like one template repeated.
    """

    def __init__(self, config: ProceduralBackgroundConfig) -> None:
        self._config = config

    @property
    def name(self) -> str:
        return PROCEDURAL_SOURCE

    def available(self) -> tuple[bool, str]:
        return True, "always available (generated, no assets required)"

    def resolve(
        self, *, seed: str, duration_seconds: float, width: int, height: int, fps: int
    ) -> BackgroundSource:
        value = seed_int(seed, "procedural")
        # Gradient axis: one of four diagonals, so the motion direction varies.
        corner = value % 4
        x0, y0 = (0, 0) if corner in (0, 1) else (width, 0)
        x1, y1 = (width, height) if corner in (0, 2) else (0, height)
        # 0.004..0.012 -- slow enough not to compete with the captions.
        speed = 0.004 + ((value >> 8) % 9) * 0.001

        spec = (
            f"gradients=s={width}x{height}:c0={_hex(self._config.top_colour)}"
            f":c1={_hex(self._config.bottom_colour)}"
            f":x0={x0}:y0={y0}:x1={x1}:y1={y1}"
            f":speed={speed:.4f}:r={fps}:d={duration_seconds:.3f}"
        )
        return BackgroundSource(
            kind="procedural",
            name=PROCEDURAL_SOURCE,
            input_args=("-f", "lavfi", "-i", spec),
        )

    @property
    def grain(self) -> float:
        return self._config.grain


class LibraryBackgroundProvider:
    """Footage from a directory of clips.

    Clips are validated once per run and cached: a directory with fifty files
    would otherwise cost fifty ffprobe spawns per video. A clip that is
    unreadable or too short is reported and skipped rather than failing the run
    -- one bad file should not stop a night's rendering.
    """

    def __init__(self, config: BackgroundConfig, *, library_dir: Path) -> None:
        self._config = config
        self._dir = library_dir
        self._clips: list[MediaInfo] | None = None

    @property
    def name(self) -> str:
        return "library"

    def clips(self) -> list[MediaInfo]:
        if self._clips is not None:
            return self._clips

        found: list[MediaInfo] = []
        if self._dir.is_dir():
            extensions = {ext.lower() for ext in self._config.extensions}
            for path in sorted(self._dir.iterdir()):
                if not path.is_file() or path.suffix.lower() not in extensions:
                    continue
                try:
                    info = probe(path)
                except Exception as exc:  # noqa: BLE001 - one bad file must not stop a run
                    _log.warning("background_clip_unreadable", clip=path.name, error=str(exc))
                    continue
                if info.duration_seconds < self._config.min_clip_seconds:
                    _log.warning(
                        "background_clip_too_short",
                        clip=path.name,
                        duration_seconds=round(info.duration_seconds, 1),
                        minimum=self._config.min_clip_seconds,
                    )
                    continue
                found.append(info)

        self._clips = found
        return found

    def available(self) -> tuple[bool, str]:
        if not self._dir.is_dir():
            return False, f"background library {self._dir} does not exist"
        usable = self.clips()
        if not usable:
            return False, f"no usable clips in {self._dir}"
        return True, f"{len(usable)} clip(s) in {self._dir}"

    # Frame geometry is fixed by the protocol; the compositor scales and crops
    # whatever clip this returns, so a library clip needs none of it.
    def resolve(
        self,
        *,
        seed: str,
        duration_seconds: float,
        width: int,  # noqa: ARG002
        height: int,  # noqa: ARG002
        fps: int,  # noqa: ARG002
    ) -> BackgroundSource:
        usable = self.clips()
        if not usable:
            raise AssetError("no usable background clips", directory=str(self._dir))

        value = seed_int(seed, "background")
        clip = usable[value % len(usable)]

        offset = 0.0
        headroom = clip.duration_seconds - duration_seconds
        if self._config.randomise_start and headroom > 1.0:
            # Quantised to whole seconds: keyframe-aligned enough to seek
            # cheaply, and varied enough that consecutive videos differ.
            offset = float((value >> 16) % int(headroom))

        looped = clip.duration_seconds < duration_seconds + offset
        args: list[str] = []
        if looped:
            args += ["-stream_loop", "-1"]
        if offset > 0:
            args += ["-ss", f"{offset:.3f}"]
        args += ["-i", str(clip.path)]

        return BackgroundSource(
            kind="library",
            name=clip.path.name,
            input_args=tuple(args),
            start_offset_seconds=offset,
            looped=looped,
        )


class AutoBackgroundProvider:
    """Library when it has footage, procedural when it does not.

    This is what makes "everything except the gameplay footage" a coherent
    state rather than a broken one: the pipeline renders complete videos today,
    and switches to real footage on the next render after files appear.
    """

    def __init__(
        self, library: LibraryBackgroundProvider, procedural: ProceduralBackgroundProvider
    ) -> None:
        self._library = library
        self._procedural = procedural

    @property
    def name(self) -> str:
        return "auto"

    @property
    def library(self) -> LibraryBackgroundProvider:
        """The clip library this provider will use once it has footage."""
        return self._library

    def available(self) -> tuple[bool, str]:
        ready, detail = self._library.available()
        if ready:
            return True, f"library: {detail}"
        return True, f"procedural ({detail})"

    def resolve(
        self, *, seed: str, duration_seconds: float, width: int, height: int, fps: int
    ) -> BackgroundSource:
        ready, _ = self._library.available()
        provider = self._library if ready else self._procedural
        return provider.resolve(
            seed=seed, duration_seconds=duration_seconds, width=width, height=height, fps=fps
        )


def build_background_provider(config: BackgroundConfig, *, library_dir: Path) -> BackgroundProvider:
    library = LibraryBackgroundProvider(config, library_dir=library_dir)
    procedural = ProceduralBackgroundProvider(config.procedural)
    if config.mode == "library":
        return library
    if config.mode == "procedural":
        return procedural
    return AutoBackgroundProvider(library, procedural)


def _hex(colour: str) -> str:
    """Normalise `#rrggbb` to the `0xRRGGBB` form ffmpeg's sources expect."""
    cleaned = colour.strip().lstrip("#")
    if len(cleaned) not in (6, 8) or not all(ch in "0123456789abcdefABCDEF" for ch in cleaned):
        raise AssetError("background colour must be #rrggbb or #rrggbbaa", colour=colour)
    return f"0x{cleaned}"


def describe_library(provider: BackgroundProvider) -> Sequence[str]:
    """Human-readable clip inventory, for `pulpmill assets`."""
    if isinstance(provider, AutoBackgroundProvider):
        provider = provider.library
    if not isinstance(provider, LibraryBackgroundProvider):
        return ()
    return tuple(
        f"{info.path.name}  {info.width}x{info.height}  {info.duration_seconds:.0f}s"
        for info in provider.clips()
    )
